### ISSUE TITLE
Use ClickHouse image for init

### ISSUE THREAD

**Issue by bmtcril** [openedx/tutor-contrib-oars#18]
The init job `oars_init_schemas_tables_users.sh` uses the oars default image but forcibly installs the clickhouse client, which takes a long time. We already have a clickhouse image in the system, so we should use that! I have no memory of what broke when I tried that last time, but it's worth fixing.

**Comment by Ian2012** [comment]
It's already fixed https://github.com/openedx/tutor-contrib-oars/blob/main/tutoroars/plugin.py#L84
