### ISSUE TITLE
OARS production configuration and testing

### ISSUE THREAD

**Issue by bmtcril** [openedx/tutor-contrib-oars#19]
There are a number of production use cases and configurations that we need to test and fix where broken. This issue is to track all of those, and they can be broken out into separate issues if the size of the work warrants it. Right now this is just collecting things in one place.

These should all be tested with each OARS script, currently the init scripts and xapi-db-load.

- [x] Test ClickHouse Cloud
- [x] Test ClickHouse over SSL
- [x] Test Ralph over SSL
- [x] Test Superset over SSL
- [ ] Test K8s, including OARS container running in a different namespace than other services
- [x] Pin image and package versions
- [x] Run a security pass on packages versions, image, and configuration

**Comment by Ian2012** [comment]
The following tasks were performed:

- Test init jobs in superset over SSL. The communication is working, the only missing piece is this issue #28 
- Test Ralph over SSL
- Pin image version and packages.

**Comment by mariajgrimaldi** [comment]
These are the checks we ran on this repo:

**Packages up-to-date:** each package must be in its latest security release.
- Pypi packages: we're covered by the requirements bot, but just for the packages found in the requirements directory. We have other requirements [here](https://github.com/openedx/tutor-contrib-oars/blob/main/tutoroars/templates/oars/apps/pythonpath/requirements.txt)  which are not being updated by the requirements bot. There's just a requirement `superset-api-client>=0.6,<0.7` which is pinned, do we have a reason for it?
- Images: OARS doesn't use docker images.
- Github actions: we planned on adding `dependabot` to update Github actions automatically like [these PRs](https://github.com/openedx/openedx-events/pulls/app%2Fdependabot) shows. 

**Configurations in plugin.py:** no hard-coded secrets/passwords. 
The passwords are generated when rendering the templates like [here](https://github.com/openedx/tutor-contrib-oars/blob/main/tutoroars/plugin.py#L50-L57). I don't see any hard coded ones.

**Scan for vulnerabilities in the implementation:** security measures are implemented. First, we ran a security analysis on a fork, which didn't say much:
![image](https://github.com/openedx/tutor-contrib-oars/assets/64440265/d78cd489-37b7-4078-a797-c053bbae7d6b)

So we manually check the scripts & python files. For the Python scripts in /templates/pythonpath, we found [this TODO](https://github.com/openedx/tutor-contrib-oars/blob/main/tutoroars/templates/oars/apps/pythonpath/superset-dashboard.py#L66-L67) tracked by [this issue](https://github.com/openedx/tutor-contrib-oars/issues/27). Is this blocking a production configuration security-wise?

**Comment by mariajgrimaldi** [comment]
@Ian2012: thanks! I missed that. Can we drop the patch from the tag image so we use the latest every time?

**Comment by mariajgrimaldi** [comment]
PR(s) regarding this issue:
- Update Python image: https://github.com/openedx/tutor-contrib-oars/pull/41
- Adding dependabot (CLA issue, we'll need to wait for it to be resolved): https://github.com/openedx/tutor-contrib-oars/pull/40
- Upgrade requirements by requirements bot: https://github.com/openedx/tutor-contrib-oars/pull/37

**Comment by bmtcril** [comment]
Thanks @mariajgrimaldi ! Once I get the event sink PR over the line I'll start reviewing and merging these. The requirements file you reference above has requirements installed in the python image for the Superset API init steps. That package doesn't seem to be super well maintained, but I think the other option is to roll our own. I'm definitely up for suggestions on how we can better do some of this, but I also know that Superset 2.1.0 is supposed to have made some significant API improvements that may simplify things if we want to try the upgrade.

**Comment by mariajgrimaldi** [comment]
> That package doesn't seem to be super well maintained, but I think the other option is to roll our own

We could contribute improvements to the existing library first. 🤔  Then, we evaluate how involved the maintainers are. If they don't answer on time then it might benefit us to maintain our library.

**Comment by bmtcril** [comment]
I think in the context of this task we're ok with that library for now. The init jobs are relatively safe, but we'll need to revisit if we go for Superset 2.1. I think the only remaining thing to do here is #28 ?

**Comment by mariajgrimaldi** [comment]
[This](https://github.com/openedx/tutor-contrib-superset/issues/30) one already has a PR. We're missing #28 then

**Comment by bmtcril** [comment]
@Ian2012 I think so, my last open question for you is whether you tested different namespaces in k8s.

**Comment by bmtcril** [comment]
It's enough for me right now, I think it may become an issue with Vector but we'll probably want to do a polish pass of testing once we have a release candidate anyway.
