### ISSUE TITLE
Bug: Non-anonymous actor ids are null

### ISSUE THREAD

**Issue by bmtcril** [openedx/tutor-contrib-oars#48]
When using the mbox or mbox hashed types, the materialized view doesn't look at the right keys to propagate the actor_id to the _parsed table. We should COALESCE those keys together here: https://github.com/openedx/tutor-contrib-oars/blob/ed5b6f3d797553a38e9cd61819bd2ca20f87f16f/tutoroars/templates/oars/jobs/init/oars_init_schemas_tables_users.sh#L59

**Comment by Ian2012** [comment]
@bmtcril Where should I add the warning and/or docs when someone change the `XAPI_AGENT_IFI_TYPE`?

**Comment by bmtcril** [comment]
We'll want to create a "concepts" doc in openedx-oars for actors (and objects, and verbs). It would live under here: https://github.com/openedx/openedx-oars/blob/8e45bce4a307736eb553715abe8d3eddc4bb58eb/docs/concepts/index.rst#L3-L2

**Comment by Ian2012** [comment]
@bmtcril https://github.com/openedx/openedx-oars/pull/54 ok, so i've added the minimal documentation around xAPI and its concepts
