### ISSUE TITLE
Investigation: How to handle actor id and email address changes

### ISSUE THREAD

**Issue by bmtcril** [openedx/tutor-contrib-oars#49]
We should document changing the actor id type in event-routing-backends invalidates all current data and how to rebuild the data. Additionally in the email based actor ids (email address and hashed email) we should have a plan for how to update the data to use the new address, or document that installations using this method will need to turn off email changes. ClickHouse hates updates, but there are some options for handling these that (so far) are all bad. This is just a placeholder since we don't know if anyone has a use case for this yet.

**Comment by Ian2012** [comment]
@bmtcril Could you include reference for the context of why clickhouse hates updates and the possible bad solutions?

**Comment by bmtcril** [comment]
This covers it all pretty well: https://altinity.com/blog/2020/4/14/handling-real-time-updates-in-clickhouse

With tracking log replay we could "simply" replay all existing log files with the new configuration and replace the whole database to solve this. That may be the best solution.

**Comment by Ian2012** [comment]
This was documented here https://github.com/openedx/openedx-oars/pull/54
