### ISSUE TITLE
Superset extensibility points

### ISSUE THREAD

**Issue by Ian2012** [openedx/tutor-contrib-oars#63]
## Description

Allow to import new dashboards/charts/datasets/databases and override existing dashboards/charts/datasets/databases based on plugins, patches, or custom mechanisms.

## Proposal

Similar to the Cairn implementation but allowing users to patch/override the json or yaml files adapting them to their necessities:

https://github.com/overhangio/tutor-cairn/blob/6f3637e34f798661d88462c0477a7e703f15cf03/tutorcairn/templates/cairn/build/cairn-superset/scripts/cairn#L212-L214

**Comment by Ian2012** [comment]
@regisb @bmtcril do you think this is the right approach?

**Comment by bmtcril** [comment]
@Ian2012 can you be more specific, maybe a pseudo-code snippet of what you'd expect would be necessary add a dashboard?

**Comment by Ian2012** [comment]
I'm currently working on a draft for a clean implementation based on what are use cases I expect to be covered. I will move the discussion to the PR once it's ready

**Comment by bmtcril** [comment]
PR is in #69 and makes sense to me, direction wise. I like that it allows patches from multiple plugins to co-exist.
