### ISSUE TITLE
Superset unable to connect to ClickHouse on fresh Tutor local

### ISSUE THREAD

**Issue by bmtcril** [openedx/tutor-contrib-oars#75]
As reported in Slack, a new Tutor Local OARS fails to connect to ClickHouse. Changing the connection string from `clickhousedb-connect://...` to `clickhousedb://...` fixes it. It's unclear why this started happening, but we should be able to update the assets to the working connection string.

**Comment by Ian2012** [comment]
Changing it in the frontend works, but importing it again didn't.

It's probably because the SUPERSET_DB_PASSWORD setting is not being used in the import process

**Comment by Ian2012** [comment]
This is fixed in the linked PR
